### ISSUE TITLE
模型import失败：ModuleNotFoundError: No module named 'native_rasterizer'

### ISSUE THREAD

**Issue by theRain0450** [zhang-tao-whu/e2ec_mmdet#3]
控制台细节：
Traceback (most recent call last):
  File "C:/PythonProject/e2ec_mmdet-master/demo/test.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\apis\__init__.py", line 2, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\apis\inference.py", line 13, in <module>
    from mmdet.datasets import replace_ImageToTensor
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\datasets\__init__.py", line 13, in <module>
    from .utils import (NumClassCheckHook, get_loading_pipeline,
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\datasets\utils.py", line 11, in <module>
    from mmdet.models.dense_heads import GARPNHead, RPNHead
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\__init__.py", line 7, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\dense_heads\__init__.py", line 17, in <module>
    from .fsaf_head import FSAFHead
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\dense_heads\fsaf_head.py", line 9, in <module>
    from ..losses.accuracy import accuracy
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\losses\__init__.py", line 21, in <module>
    from .contour_loss import DMLoss, MaskRasterizationLoss
  File "C:\PythonProject\e2ec_mmdet-master\mmdet\models\losses\contour_loss.py", line 8, in <module>
    import native_rasterizer
ModuleNotFoundError: No module named 'native_rasterizer'

**Comment by zhang-tao-whu** [comment]
Please cd to [dir](https://github.com/zhang-tao-whu/e2ec_mmdet/tree/master/csrc/diff_ras) and install it (```python setup.py develop```).

**Comment by theRain0450** [comment]
> Please cd to [dir](https://github.com/zhang-tao-whu/e2ec_mmdet/tree/master/csrc/diff_ras) and install it (`python setup.py develop`).

sorry，it still not work
![image](https://github.com/zhang-tao-whu/e2ec_mmdet/assets/129521175/883b8d0b-5e3d-47ee-85e4-8a6722815247)
![image](https://github.com/zhang-tao-whu/e2ec_mmdet/assets/129521175/182fb8c4-3032-4866-9cca-61815162f815)
![image](https://github.com/zhang-tao-whu/e2ec_mmdet/assets/129521175/574373bf-bd94-46d1-87cf-056fb8f10866)

**Comment by shaomingshun** [comment]
> > Please cd to [dir](https://github.com/zhang-tao-whu/e2ec_mmdet/tree/master/csrc/diff_ras) and install it (`python setup.py develop`).
> 
> sorry，it still not work ![image](https://private-user-images.githubusercontent.com/129521175/297372257-883b8d0b-5e3d-47ee-85e4-8a6722815247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODAxOTUsIm5iZiI6MTczNDc3OTg5NSwicGF0aCI6Ii8xMjk1MjExNzUvMjk3MzcyMjU3LTg4M2I4ZDBiLTVlM2QtNDdlZS04NWU0LThhNjcyMjgxNTI0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMTE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzU2MWRkZjI3ZTFiNTY3MzM3YmNkZjEyNDUyMTVhMDgzNzJlNGQ3YmJiYmExYjE4MzU2NWI0Njk1Mzk1ZTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xcOefJRDKh7gYk_5ja8rD7d6Vg4mhiRs_iQKRYFvJ0w) ![image](https://private-user-images.githubusercontent.com/129521175/297372292-182fb8c4-3032-4866-9cca-61815162f815.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODAxOTUsIm5iZiI6MTczNDc3OTg5NSwicGF0aCI6Ii8xMjk1MjExNzUvMjk3MzcyMjkyLTE4MmZiOGM0LTMwMzItNDg2Ni05Y2NhLTYxODE1MTYyZjgxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMTE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTI2MjY1YzljOGQ2OWQwMDU2MzNlOGU1MTA0YjViZWEwYjAxZTMwNjAzYzM2ZTM5Y2VhZmVlMmYzYzBmOWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yj9cTA7-QeLKEPDwJD92hS27fEnCLR8021zzV665vtc) ![image](https://private-user-images.githubusercontent.com/129521175/297372553-574373bf-bd94-46d1-87cf-056fb8f10866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3ODAxOTUsIm5iZiI6MTczNDc3OTg5NSwicGF0aCI6Ii8xMjk1MjExNzUvMjk3MzcyNTUzLTU3NDM3M2JmLWJkOTQtNDZkMS04N2NmLTA1NmZiOGYxMDg2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxMTE4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg0ZTg0NjMzNzlmNTMzYzNlZDg3MmUxOTgyYzQyMTcwODllMWJmYjc4MjhlNDhiMTk0MDZjMWM3MTdiZTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zFe8XRIqrKrkdCTNTl5bmURLqrcQilzj9dqzsUXCkM4)

我找到问题所在了，你应该进入目录下的csrc/diff_ras文件，并执行python setup.py build develop
![Snipaste_2024-12-21_19-29-05](https://github.com/user-attachments/assets/00cb2c9f-d106-46fb-85e4-9e366005a393)
